[versions]

# Android
compileSdk = "36"
targetSdk = "36"
minSdk = "26"

# Libraries
kotlin = "2.2.21"
coreKtx = "1.17.0"
composeBom = "2025.12.00"
composeNavigation = "2.9.6"
kotlinSerialization = "1.9.0"
hilt = "2.57.2"
hiltNavigation = "1.3.0"
room = "2.8.4"
timber = "5.0.1"
firebaseBom = "34.6.0"
lifecycle = "2.10.0"
datastore = "1.2.0"
splashscreen = "1.2.0"
retrofit = "3.0.0"
retrofitSerializationConverter = "1.0.0"
okhttpBom = "5.3.2"
coil = "3.3.0"
coil-okhttp = "3.3.0"

# Tests
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
accompanist = "0.37.3"
mlkit = "17.3.0"
camera = "1.5.2"

# Plugins
agp = "8.13.1"
ksp = "2.3.3"
googleServices = "4.4.4"
firebaseCrashlyticsPlugin = "3.0.6"
firebaseAppdistributionPlugin = "5.2.0"
easylauncherPlugin = "6.4.1"
stabilityAnalyzer = "0.6.0"

[libraries]
# AndroidX
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" } # DEBUG ONLY
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }

# Compose navigation
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }

# Serialization
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

# Timber
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-database = { module = "com.google.firebase:firebase-database" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitSerializationConverter" }

# Okhttp
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }

# Coil
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil-okhttp" }

# Datastore
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# SplashScreen
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

# Accompanist
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

# Camera
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-compose = { module = "androidx.camera:camera-compose", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }

# MLKit
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppdistributionPlugin" }
easylauncher = { id = "com.starter.easylauncher", version.ref = "easylauncherPlugin" }
stability-analyzer = { id = "com.github.skydoves.compose.stability.analyzer", version.ref = "stabilityAnalyzer" }

[bundles]
compose = ["androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-ui-tooling-preview", "androidx-compose-material3"]
coil = ["coil", "coil-okhttp"]
datastore = ["datastore", "datastore-preferences"]
camera = ["camera-core", "camera-compose", "camera-lifecycle", "camera-camera2", "camera-view"]